import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "./providers/provider";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Universe Of Ideas",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <Providers>

          <Header />
          {children}
        </Providers>

      </body>

    </html >
  );
}
